#!/usr/bin/env python3
"""Helix tower generator: alternating cyclotomic (rotation) + Kummer layers.

User conjecture: tower ⊕ cyclotomic = double-helix; ζ_p provides rotation,
ⁿ√a layers extend the helix; Galois group = semidirect products generated by
the rotation action. This makes the group structure CONTROLLED (vs random
towers which collapse to the generic group).

Layer scheme (degree 24 = 2·3·2·2):
  K0 = Q(ζ3)                 (cyclotomic layer, degree 2, rotation 120°)
  K1 = K0(∛a),  a ∈ K0       (Kummer C3 layer, ζ3 ∈ K0 → cyclic, rotation)
  K2 = K1(√b),  b ∈ K1       (quadratic layer)
  K3 = K2(√c),  c ∈ K2       (quadratic layer, degree 24)

Variant flag selects which element classes are used for a/b/c:
  v1: random elements (small coeffs)
  v2: a = γ²·ζ3  (rotation-twisted), b,c random — helix with explicit twist
"""
import math, random, sys
sys.set_int_max_str_digits(10**7)
from cypari2 import Pari

pari = Pari()
X, Y, Z = pari("x"), pari("y"), pari("z")
SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 20260822
VARIANT = int(sys.argv[3]) if len(sys.argv) > 3 else 1

def is_irred(g):
    try: return bool(g.polisirreducible())
    except Exception: return False

def real_count(g):
    try: return int(pari.polsturm(g))
    except Exception: return -1

def prim_part(c):
    gg = 0
    for z in c:
        gg = math.gcd(gg, abs(z))
    if gg > 1:
        return [z // gg for z in c]
    return c

def poly_layer(f, bcoeffs, kth):
    """Res_y(f(y), z^k − b(y)) with z→x; monic degree k·deg(f) poly."""
    d = f.poldegree()
    fy = pari.subst(f, X, Y)
    b = pari.Pol(bcoeffs, Y)
    coeffs = [Z**kth - bcoeffs[0]] + [-bcoeffs[i] for i in range(1, d)]
    g = pari.Pol(coeffs, Y)
    try:
        R = pari.polresultant(fy, g, Y)
    except Exception:
        return None
    R = pari.subst(R, Z, X)
    if R.poldegree() != kth * d:
        return None
    c = [int(z) for z in pari.Vecrev(pari.Pol(R, X))]
    c = prim_part(c)
    P = pari.Polrev(c)
    if not is_irred(P):
        return None
    if kth * d <= 12:
        try:
            Pr = pari.polredabs(P)
        except Exception:
            Pr = P
        if Pr.poldegree() == kth * d:
            P = Pr
    cc = [int(z) for z in pari.Vecrev(pari.Pol(P, X))]
    if any(abs(z) > 10**40 for z in cc):
        return None
    return cc

def rand_elem(f, rng, bound=5):
    d = f.poldegree()
    for _ in range(40):
        bc = [rng.randint(-bound, bound) for _ in range(d)]
        if all(z == 0 for z in bc):
            continue
        return bc
    return None

def twist_elem(f, rng, bound=4):
    """γ²·ζ3 mod f (explicit rotation twist): b = γ² · zeta3."""
    d = f.poldegree()
    fy = pari.subst(f, X, Y)
    for _ in range(40):
        gc = [rng.randint(-bound, bound) for _ in range(d)]
        if all(z == 0 for z in gc):
            continue
        gam = pari.Pol(gc, Y)
        b = (gam * gam * Y) % fy  # γ² · y  (y = ζ3 in Q[x]/(f) when f=x²+x+1)
        bc = [int(z) for z in pari.Vecrev(pari.Pol(b, Y))]
        while len(bc) < d:
            bc.append(0)
        return bc
    return None

def main():
    rng = random.Random(SEED)
    out = []
    seen = set()
    made = 0
    tries = 0
    n_target = int(sys.argv[2]) if len(sys.argv) > 2 else 100
    while made < n_target and tries < 4000:
        tries += 1
        # L0 = Q(ζ3)
        f0 = pari.Polrev([1, 1, 1])  # x²+x+1, degree 2
        # L1 = L0(∛a)
        if VARIANT == 2:
            bc = twist_elem(f0, rng)
        else:
            bc = rand_elem(f0, rng)
        if bc is None: continue
        c = poly_layer(f0, bc, 3)
        if c is None: continue
        f1 = pari.Polrev(c)  # degree 6
        # L2 = L1(√b)
        bc = rand_elem(f1, rng, bound=3)
        if bc is None: continue
        c = poly_layer(f1, bc, 2)
        if c is None: continue
        f2 = pari.Polrev(c)  # degree 12
        # L3 = L2(√c)
        bc = rand_elem(f2, rng, bound=3)
        if bc is None: continue
        c = poly_layer(f2, bc, 2)
        if c is None: continue
        if len(c) != 25: continue
        lc = c[24]
        if lc == 1: pass
        elif lc == -1: c = [-z for z in c]
        elif all(z % lc == 0 for z in c): c = [z // lc for z in c]
        else:
            out2 = []
            for k in range(24):
                out2.append(c[k] * lc ** (23 - k))
            out2.append(1)
            c = out2
        key = tuple(c)
        if key in seen: continue
        if c[0] == 0: continue
        g = pari.Polrev(c)
        if not is_irred(g): continue
        r = real_count(g)
        if r < 0 or r % 2 != 0: continue
        seen.add(key)
        out.append((c, f"helix_v{VARIANT}"))
        made += 1
    print(f"helix_v{VARIANT}: made={made} tries={tries}", file=sys.stderr)
    for c, tag in out:
        r = real_count(pari.Polrev(c))
        print(",".join(str(z) for z in c) + f" # {tag} r={r}")

if __name__ == "__main__":
    main()
